### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/year-of-making#2]
- [x] Make bot to grab YouTube from @realhenrysnow and @richlitt
- [x] Make a bot to grab Twitter links with squarespace link and #blog
- [ ] Make a bot to grab Twitter links from TinyLetter  
- [ ] Display on a website

**Comment by RichardLitt** [comment]
Closing as irrelevant. Website looks good.
